In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
import os

import duckdb as dd
import polars as pl
from skimpy import skim

from src.config import *
from src.const import (CATEGORICAL_NOMINAL_VARS, CATEGORICAL_ORDINAL_VARS,
                       NUMERICAL_CONTINUOUS_VARS, NUMERICAL_DISCRETE_VARS,
                       PRIMARY_KEY, TIME_VARS)
from src.data.dqa import data_quality_assessment
from src.data.schema import CreditCardBalanceSchema

In [13]:
# Establish DuckDB connection
os.chdir(DATABASE_DIR)
con = dd.connect(HOME_CREDIT_DB)
con

# **Data Wrangling**

In [14]:
query = "SELECT * FROM credit_card_balance"
df = con.sql(query).pl()

## **Data Diagnosis**

In [4]:
skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                 Data Types                                                                │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                         │
│ ┃ Dataframe         ┃ Values  ┃ ┃ Column Type ┃ Count ┃                                                         │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                         │
│ │ Number of rows    │ 3840312 │ │ float64     │ 15    │                                                         │
│ │ Number of columns │ 23      │ │ int64       │ 7     │                                                         │
│ └───────────────────┴─────────┘ │ string      │ 1     │                                                         │
│                                 └─────────────┴───────┘                                                         │
│                                                     number                                                      │
│ ┏━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓  │
│ ┃ column  ┃ NA     ┃ NA %     ┃ mean    ┃ sd      ┃ p0      ┃ p25     ┃ p50     ┃ p75     ┃ p100    ┃ hist   ┃  │
│ ┡━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩  │
│ │ SK_ID_P │      0 │        0 │ 1905000 │  536500 │ 1000000 │ 1434000 │ 1897000 │ 2369000 │ 2843000 │ ▇▇▇▇▇▇ │  │
│ │ REV     │        │          │         │         │         │         │         │         │         │        │  │
│ │ SK_ID_C │      0 │        0 │  278300 │  102700 │  100000 │  189500 │  278400 │  367600 │  456200 │ ▇▇▇▇▇▇ │  │
│ │ URR     │        │          │         │         │         │         │         │         │         │        │  │
│ │ MONTHS_ │      0 │        0 │  -34.52 │   26.67 │     -96 │     -55 │     -28 │     -11 │      -1 │ ▂▃▃▃▅▇ │  │
│ │ BALANCE │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_BAL │      0 │        0 │   58300 │  106300 │ -420300 │       0 │       0 │   89050 │ 1506000 │   ▇▁   │  │
│ │ ANCE    │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_CRE │      0 │        0 │  153800 │  165100 │       0 │   45000 │  112500 │  180000 │ 1350000 │  ▇▁▁   │  │
│ │ DIT_LIM │        │          │         │         │         │         │         │         │         │        │  │
│ │ IT_ACTU │        │          │         │         │         │         │         │         │         │        │  │
│ │ AL      │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_DRA │ 749816 │ 19.52487 │    5961 │   28230 │   -6827 │       0 │       0 │       0 │ 2115000 │   ▇    │  │
│ │ WINGS_A │        │ 19374884 │         │         │         │         │         │         │         │        │  │
│ │ TM_CURR │        │       13 │         │         │         │         │         │         │         │        │  │
│ │ ENT     │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_DRA │      0 │        0 │    7433 │   33850 │   -6212 │       0 │       0 │       0 │ 2287000 │   ▇    │  │
│ │ WINGS_C │        │          │         │         │         │         │         │         │         │        │  │
│ │ URRENT  │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_DRA │ 749816 │ 19.52487 │   288.2 │    8202 │       0 │       0 │       0 │       0 │ 1530000 │   ▇    │  │
│ │ WINGS_O │        │ 19374884 │         │         │         │         │         │         │         │        │  │
│ │ THER_CU │        │       13 │         │         │         │         │         │         │         │        │  │
│ │ RRENT   │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_DRA │ 749816 │ 19.52487 │    2969 │   20800 │       0 │       0 │       0 │       0 │ 2239000 │   ▇    │  │
│ │ WINGS_P │        │ 19374884 │         │         │         │         │         │         │         │        │  │
│ │ OS_CURR │        │       13 │         │         │         │         │         │         │         │        │  │
│ │ ENT     │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_INS │ 305236 │ 7.948208 │    3540 │    5600 │       0 │       0 │       0 │    6634 │  202900 │   ▇    │  │
│ │ T_MIN_R │        │ 37473621 │         │         │         │         │         │         │         │        │  │
│ │ EGULARI │        │        9 │         │         │         │         │         │         │         │        │  │
│ │ TY      │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_PAY │ 767988 │ 19.99806 │   10280 │   36080 │       0 │   152.4 │    2703 │    9000 │ 4289000 │   ▇    │  │
│ │ MENT_CU │        │ 26574090 │         │         │         │         │         │         │         │        │  │
│ │ RRENT   │        │       86 │         │         │         │         │         │         │         │        │  │
│ │ AMT_PAY │      0 │        0 │    7589 │   32010 │       0 │       0 │       0 │    6750 │ 4278000 │   ▇    │  │
│ │ MENT_TO │        │          │         │         │         │         │         │         │         │        │  │
│ │ TAL_CUR │        │          │         │         │         │         │         │         │         │        │  │
│ │ RENT    │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_REC │      0 │        0 │   55970 │  102500 │ -423300 │       0 │       0 │   85360 │ 1472000 │   ▇▁   │  │
│ │ EIVABLE │        │          │         │         │         │         │         │         │         │        │  │
│ │ _PRINCI │        │          │         │         │         │         │         │         │         │        │  │
│ │ PAL     │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_REC │      0 │        0 │   58090 │  106000 │ -420300 │       0 │       0 │   88900 │ 1493000 │   ▇▁   │  │
│ │ IVABLE  │        │          │         │         │         │         │         │         │         │        │  │
│ │ AMT_TOT │      0 │        0 │   58100 │  106000 │ -420300 │       0 │       0 │   88910 │ 1493000 │   ▇▁   │  │
│ │ AL_RECE │        │          │         │         │         │         │         │         │         │        │  │
│ │ IVABLE  │        │          │         │         │         │         │         │         │         │        │  │
│ │ CNT_DRA │ 749816 │ 19.52487 │  0.3094 │     1.1 │       0 │       0 │       0 │       0 │      51 │   ▇    │  │
│ │ WINGS_A │        │ 19374884 │         │         │         │         │         │         │         │        │  │
│ │ TM_CURR │        │       13 │         │         │         │         │         │         │         │        │  │
│ │ ENT     │        │          │         │         │         │         │         │         │         │        │  │
│ │ CNT_DRA │      0 │        0 │  0.7031 │    3.19 │       0 │       0 │       0 │       0 │     165 │   ▇    │  │
│ │ WINGS_C │        │          │         │         │         │         │         │         │         │        │  │
│ │ URRENT  │        │          │         │         │         │         │         │         │         │        │  │
│ │ CNT_DRA │ 749816 │ 19.52487 │ 0.00481 │ 0.08264 │       0 │       0 │       0 │       0 │      12 │   ▇    │  │
│ │ WINGS_O │        │ 19374884 │       2 │         │         │         │         │         │         │        │  │
│ │ THER_CU │        │       13 │         │         │         │         │         │         │         │        │  │
│ │ RRENT   │        │          │         │         │         │         │         │         │         │        │  │
│ │ CNT_DRA │ 749816 │ 19.52487 │  0.5595 │   3.241 │       0 │       0 │       0 │       0 │     165 │   ▇    │  │
│ │ WINGS_P │        │ 19374884 │         │         │         │         │         │         │         │        │  │
│ │ OS_CURR │        │       13 │         │         │         │         │         │         │         │        │  │
│ │ ENT     │        │          │         │         │         │         │         │         │         │        │  │
│ │ CNT_INS │ 305236 │ 7.948208 │   20.83 │   20.05 │       0 │       4 │      15 │      32 │     120 │  ▇▃▂▁  │  │
│ │ TALMENT │        │ 37473621 │         │         │         │         │         │         │         │        │  │
│ │ _MATURE │        │        9 │         │         │         │         │         │         │         │        │  │
│ │ _CUM    │        │          │         │         │         │         │         │         │         │        │  │
│ │ SK_DPD  │      0 │        0 │   9.284 │   97.52 │       0 │       0 │       0 │       0 │    3260 │   ▇    │  │
│ │ SK_DPD_ │      0 │        0 │  0.3316 │   21.48 │       0 │       0 │       0 │       0 │    3260 │   ▇    │  │
│ │ DEF     │        │          │         │         │         │         │         │         │         │        │  │
│ └─────────┴────────┴──────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃             ┃    ┃      ┃          ┃             ┃        ┃        ┃ chars per  ┃ words per   ┃ total      ┃  │
│ ┃ column      ┃ NA ┃ NA % ┃ shortest ┃ longest     ┃ min    ┃ max    ┃ row        ┃ row         ┃ words      ┃  │
│ ┡━━━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │ NAME_CONTRA │  0 │    0 │ Active   │ Sent        │ Active │ Signed │        6.1 │           1 │    3840825 │  │
│ │ CT_STATUS   │    │      │          │ proposal    │        │        │            │             │            │  │
│ └─────────────┴────┴──────┴──────────┴─────────────┴────────┴────────┴────────────┴─────────────┴────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [16]:
df.glimpse()

Rows: 3840312
Columns: 23
$ SK_ID_PREV                 <i64> 2562384, 2582071, 1740877, 1389973, 1891521, 2646502, 1079071, 2095912, 2181852, 1235299
$ SK_ID_CURR                 <i64> 378907, 363914, 371185, 337855, 126868, 380010, 171320, 118650, 367360, 203885
$ MONTHS_BALANCE             <i64> -6, -1, -7, -4, -1, -7, -6, -7, -4, -5
$ AMT_BALANCE                <f64> 56.97, 63975.555, 31815.225, 236572.11, 453919.455, 82903.815, 353451.645, 47962.125, 291543.075, 201261.195
$ AMT_CREDIT_LIMIT_ACTUAL    <i64> 135000, 45000, 450000, 225000, 450000, 270000, 585000, 45000, 292500, 225000
$ AMT_DRAWINGS_ATM_CURRENT   <f64> 0.0, 2250.0, 0.0, 2250.0, 0.0, 0.0, 67500.0, 45000.0, 90000.0, 76500.0
$ AMT_DRAWINGS_CURRENT       <f64> 877.5, 2250.0, 0.0, 2250.0, 11547.0, 0.0, 67500.0, 45000.0, 289339.425, 111026.7
$ AMT_DRAWINGS_OTHER_CURRENT <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ AMT_DRAWINGS_POS_CURRENT   <f64> 877.5, 0.0, 0.0, 0.0, 11547.0, 0.0, 0.0, 0.0, 199339.425, 34526.7
$ AMT_INST_MIN_REGULARITY    <f64> 1700.325, 2250.0, 2250.0, 11795.76, 22924.89, 4449.105, 14684.175, 0.0, 130.5, 6338.34
$ AMT_PAYMENT_CURRENT        <f64> 1800.0, 2250.0, 2250.0, 11925.0, 27000.0, 3825.0, 15750.0, 264.69, 4093.515, 45000.0
$ AMT_PAYMENT_TOTAL_CURRENT  <f64> 1800.0, 2250.0, 2250.0, 11925.0, 27000.0, 3825.0, 15750.0, 0.0, 4093.515, 45000.0
$ AMT_RECEIVABLE_PRINCIPAL   <f64> 0.0, 60175.08, 26926.425, 224949.285, 443044.395, 80519.04, 345433.86, 44735.31, 285376.41, 192793.275
$ AMT_RECIVABLE              <f64> 0.0, 64875.555, 31460.085, 233048.97, 453919.455, 82773.315, 351881.145, 47962.125, 286831.575, 197224.695
$ AMT_TOTAL_RECEIVABLE       <f64> 0.0, 64875.555, 31460.085, 233048.97, 453919.455, 82773.315, 351881.145, 47962.125, 286831.575, 197224.695
$ CNT_DRAWINGS_ATM_CURRENT   <f64> 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 3.0, 3.0
$ CNT_DRAWINGS_CURRENT       <i64> 1, 1, 0, 1, 1, 0, 1, 1, 8, 9
$ CNT_DRAWINGS_OTHER_CURRENT <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ CNT_DRAWINGS_POS_CURRENT   <f64> 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 5.0, 6.0
$ CNT_INSTALMENT_MATURE_CUM  <f64> 35.0, 69.0, 30.0, 10.0, 101.0, 2.0, 6.0, 51.0, 3.0, 38.0
$ NAME_CONTRACT_STATUS       <str> 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active'
$ SK_DPD                     <i64> 0, 0, 0, 0, 0, 7, 0, 0, 0, 0
$ SK_DPD_DEF                 <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [6]:
df.shape

(3840312, 23)

In [7]:
df.schema

Schema([('SK_ID_PREV', Int64),
        ('SK_ID_CURR', Int64),
        ('MONTHS_BALANCE', Int64),
        ('AMT_BALANCE', Float64),
        ('AMT_CREDIT_LIMIT_ACTUAL', Int64),
        ('AMT_DRAWINGS_ATM_CURRENT', Float64),
        ('AMT_DRAWINGS_CURRENT', Float64),
        ('AMT_DRAWINGS_OTHER_CURRENT', Float64),
        ('AMT_DRAWINGS_POS_CURRENT', Float64),
        ('AMT_INST_MIN_REGULARITY', Float64),
        ('AMT_PAYMENT_CURRENT', Float64),
        ('AMT_PAYMENT_TOTAL_CURRENT', Float64),
        ('AMT_RECEIVABLE_PRINCIPAL', Float64),
        ('AMT_RECIVABLE', Float64),
        ('AMT_TOTAL_RECEIVABLE', Float64),
        ('CNT_DRAWINGS_ATM_CURRENT', Float64),
        ('CNT_DRAWINGS_CURRENT', Int64),
        ('CNT_DRAWINGS_OTHER_CURRENT', Float64),
        ('CNT_DRAWINGS_POS_CURRENT', Float64),
        ('CNT_INSTALMENT_MATURE_CUM', Float64),
        ('NAME_CONTRACT_STATUS', String),
        ('SK_DPD', Int64),
        ('SK_DPD_DEF', Int64)])

In [8]:
df.columns

['SK_ID_PREV',
 'SK_ID_CURR',
 'MONTHS_BALANCE',
 'AMT_BALANCE',
 'AMT_CREDIT_LIMIT_ACTUAL',
 'AMT_DRAWINGS_ATM_CURRENT',
 'AMT_DRAWINGS_CURRENT',
 'AMT_DRAWINGS_OTHER_CURRENT',
 'AMT_DRAWINGS_POS_CURRENT',
 'AMT_INST_MIN_REGULARITY',
 'AMT_PAYMENT_CURRENT',
 'AMT_PAYMENT_TOTAL_CURRENT',
 'AMT_RECEIVABLE_PRINCIPAL',
 'AMT_RECIVABLE',
 'AMT_TOTAL_RECEIVABLE',
 'CNT_DRAWINGS_ATM_CURRENT',
 'CNT_DRAWINGS_CURRENT',
 'CNT_DRAWINGS_OTHER_CURRENT',
 'CNT_DRAWINGS_POS_CURRENT',
 'CNT_INSTALMENT_MATURE_CUM',
 'NAME_CONTRACT_STATUS',
 'SK_DPD',
 'SK_DPD_DEF']

In [10]:
df.null_count()

shape: (1, 23)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ SK_ID_PREV ┆ SK_ID_CURR ┆ MONTHS_BA ┆ AMT_BALAN ┆ … ┆ CNT_INSTA ┆ NAME_CONT ┆ SK_DPD ┆ SK_DPD_DE │
│ ---        ┆ ---        ┆ LANCE     ┆ CE        ┆   ┆ LMENT_MAT ┆ RACT_STAT ┆ ---    ┆ F         │
│ u32        ┆ u32        ┆ ---       ┆ ---       ┆   ┆ URE_CUM   ┆ US        ┆ u32    ┆ ---       │
│            ┆            ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆        ┆ u32       │
│            ┆            ┆           ┆           ┆   ┆ u32       ┆ u32       ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 0          ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 305236    ┆ 0         ┆ 0      ┆ 0         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [11]:
df.describe()

shape: (9, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ SK_ID_PRE ┆ SK_ID_CUR ┆ MONTHS_BA ┆ … ┆ CNT_INSTA ┆ NAME_CONT ┆ SK_DPD    ┆ SK_DPD_D │
│ ---       ┆ V         ┆ R         ┆ LANCE     ┆   ┆ LMENT_MAT ┆ RACT_STAT ┆ ---       ┆ EF       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ URE_CUM   ┆ US        ┆ f64       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆           ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.840312e ┆ 3.840312e ┆ 3.840312e ┆ … ┆ 3.535076e ┆ 3840312   ┆ 3.840312e ┆ 3.840312 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆           ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 305236.0  ┆ 0         ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.9045e6  ┆ 278324.20 ┆ -34.52192 ┆ … ┆ 20.825084 ┆ null      ┆ 9.283667  ┆ 0.331622 │
│           ┆           ┆ 7289      ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 536469.47 ┆ 102704.47 ┆ 26.667751 ┆ … ┆ 20.051494 ┆ null      ┆ 97.5157   ┆ 21.47923 │
│           ┆ 0563      ┆ 5133      ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ min       ┆ 1.000018e ┆ 100006.0  ┆ -96.0     ┆ … ┆ 0.0       ┆ Active    ┆ 0.0       ┆ 0.0      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 1.434385e ┆ 189517.0  ┆ -55.0     ┆ … ┆ 4.0       ┆ null      ┆ 0.0       ┆ 0.0      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 1.897122e ┆ 278396.0  ┆ -28.0     ┆ … ┆ 15.0      ┆ null      ┆ 0.0       ┆ 0.0      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.369324e ┆ 367580.0  ┆ -11.0     ┆ … ┆ 32.0      ┆ null      ┆ 0.0       ┆ 0.0      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 2.843496e ┆ 456250.0  ┆ -1.0      ┆ … ┆ 120.0     ┆ Signed    ┆ 3260.0    ┆ 3260.0   │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### **Numerical Variables**

In [19]:
## Discrete Variables
for col in NUMERICAL_DISCRETE_VARS:
    print(col)
    print(df[col].n_unique())
    print(df[col].value_counts(normalize=True).sort(col))
    print("\n")

MONTHS_BALANCE
96
shape: (96, 2)
┌────────────────┬────────────┐
│ MONTHS_BALANCE ┆ proportion │
│ ---            ┆ ---        │
│ i64            ┆ f64        │
╞════════════════╪════════════╡
│ -96            ┆ 0.003052   │
│ -95            ┆ 0.00326    │
│ -94            ┆ 0.003489   │
│ -93            ┆ 0.003697   │
│ -92            ┆ 0.003883   │
│ …              ┆ …          │
│ -5             ┆ 0.026182   │
│ -4             ┆ 0.02659    │
│ -3             ┆ 0.026132   │
│ -2             ┆ 0.024645   │
│ -1             ┆ 0.016237   │
└────────────────┴────────────┘


CNT_DRAWINGS_ATM_CURRENT
45
shape: (45, 2)
┌──────────────────────────┬────────────┐
│ CNT_DRAWINGS_ATM_CURRENT ┆ proportion │
│ ---                      ┆ ---        │
│ f64                      ┆ f64        │
╞══════════════════════════╪════════════╡
│ null                     ┆ 0.195249   │
│ 0.0                      ┆ 0.694141   │
│ 1.0                      ┆ 0.055584   │
│ 2.0                      ┆ 0.024906   │
│ 3.0                      ┆ 0.012168   │
│ …                        ┆ …          │
│ 39.0                     ┆ 5.2079e-7  │
│ 41.0                     ┆ 5.2079e-7  │
│ 43.0                     ┆ 2.6040e-7  │
│ 44.0                     ┆ 2.6040e-7  │
│ 51.0                     ┆ 2.6040e-7  │
└──────────────────────────┴────────────┘


CNT_DRAWINGS_CURRENT
129
shape: (129, 2)
┌──────────────────────┬────────────┐
│ CNT_DRAWINGS_CURRENT ┆ proportion │
│ ---                  ┆ ---        │
│ i64                  ┆ f64        │
╞══════════════════════╪════════════╡
│ 0                    ┆ 0.841065   │
│ 1                    ┆ 0.060234   │
│ 2                    ┆ 0.030404   │
│ 3                    ┆ 0.017009   │
│ 4                    ┆ 0.011273   │
│ …                    ┆ …          │
│ 142                  ┆ 5.2079e-7  │
│ 143                  ┆ 2.6040e-7  │
│ 151                  ┆ 2.6040e-7  │
│ 162                  ┆ 5.2079e-7  │
│ 165                  ┆ 2.6040e-7  │
└──────────────────────┴────────────┘


CNT_DRAWINGS_OTHER_CURRENT
12
shape: (12, 2)
┌────────────────────────────┬────────────┐
│ CNT_DRAWINGS_OTHER_CURRENT ┆ proportion │
│ ---                        ┆ ---        │
│ f64                        ┆ f64        │
╞════════════════════════════╪════════════╡
│ null                       ┆ 0.195249   │
│ 0.0                        ┆ 0.801416   │
│ 1.0                        ┆ 0.002957   │
│ 2.0                        ┆ 0.00028    │
│ 3.0                        ┆ 0.000067   │
│ …                          ┆ …          │
│ 6.0                        ┆ 0.000003   │
│ 7.0                        ┆ 0.000002   │
│ 8.0                        ┆ 7.8119e-7  │
│ 10.0                       ┆ 7.8119e-7  │
│ 12.0                       ┆ 2.6040e-7  │
└────────────────────────────┴────────────┘


CNT_DRAWINGS_POS_CURRENT
134
shape: (134, 2)
┌──────────────────────────┬────────────┐
│ CNT_DRAWINGS_POS_CURRENT ┆ proportion │
│ ---                      ┆ ---        │
│ f64                      ┆ f64        │
╞══════════════════════════╪════════════╡
│ null                     ┆ 0.195249   │
│ 0.0                      ┆ 0.735772   │
│ 1.0                      ┆ 0.018805   │
│ 2.0                      ┆ 0.010692   │
│ 3.0                      ┆ 0.007118   │
│ …                        ┆ …          │
│ 142.0                    ┆ 2.6040e-7  │
│ 143.0                    ┆ 2.6040e-7  │
│ 151.0                    ┆ 2.6040e-7  │
│ 162.0                    ┆ 5.2079e-7  │
│ 165.0                    ┆ 2.6040e-7  │
└──────────────────────────┴────────────┘


CNT_INSTALMENT_MATURE_CUM
122
shape: (122, 2)
┌───────────────────────────┬────────────┐
│ CNT_INSTALMENT_MATURE_CUM ┆ proportion │
│ ---                       ┆ ---        │
│ f64                       ┆ f64        │
╞═══════════════════════════╪════════════╡
│ null                      ┆ 0.079482   │
│ 0.0                       ┆ 0.1436     │
│ 1.0                       ┆ 0.022734   │
│ 2.0                       ┆ 0.023705   │
│ 3.0                       ┆ 0.023303   │
│ …                         ┆ …          │
│ 116.0                     ┆ 0.000002   │
│ 117.0                     ┆ 0.000001   │
│ 118.0                     ┆ 7.8119e-7  │
│ 119.0                     ┆ 5.2079e-7  │
│ 120.0                     ┆ 2.6040e-7  │
└───────────────────────────┴────────────┘


SK_DPD
917
shape: (917, 2)
┌────────┬────────────┐
│ SK_DPD ┆ proportion │
│ ---    ┆ ---        │
│ i64    ┆ f64        │
╞════════╪════════════╡
│ 0      ┆ 0.960067   │
│ 1      ┆ 0.023532   │
│ 5      ┆ 0.000139   │
│ 6      ┆ 0.000026   │
│ 7      ┆ 0.000468   │
│ …      ┆ …          │
│ 3137   ┆ 2.6040e-7  │
│ 3168   ┆ 2.6040e-7  │
│ 3198   ┆ 2.6040e-7  │
│ 3229   ┆ 2.6040e-7  │
│ 3260   ┆ 2.6040e-7  │
└────────┴────────────┘


SK_DPD_DEF
378
shape: (378, 2)
┌────────────┬────────────┐
│ SK_DPD_DEF ┆ proportion │
│ ---        ┆ ---        │
│ i64        ┆ f64        │
╞════════════╪════════════╡
│ 0          ┆ 0.976736   │
│ 1          ┆ 0.021634   │
│ 5          ┆ 0.000106   │
│ 6          ┆ 0.000022   │
│ 7          ┆ 0.000306   │
│ …          ┆ …          │
│ 3137       ┆ 2.6040e-7  │
│ 3168       ┆ 2.6040e-7  │
│ 3198       ┆ 2.6040e-7  │
│ 3229       ┆ 2.6040e-7  │
│ 3260       ┆ 2.6040e-7  │
└────────────┴────────────┘

In [20]:
## Continuous Variables
for col in NUMERICAL_CONTINUOUS_VARS:
    print(col)
    print(df[col].n_unique())
    print(df[col].value_counts(normalize=True).sort(col))
    print("\n")

AMT_BALANCE
1347904
shape: (1_347_904, 2)
┌─────────────┬────────────┐
│ AMT_BALANCE ┆ proportion │
│ ---         ┆ ---        │
│ f64         ┆ f64        │
╞═════════════╪════════════╡
│ -420250.185 ┆ 2.6040e-7  │
│ -261471.015 ┆ 2.6040e-7  │
│ -259848.945 ┆ 2.6040e-7  │
│ -240305.985 ┆ 2.6040e-7  │
│ -223224.21  ┆ 5.2079e-7  │
│ …           ┆ …          │
│ 1.3293e6    ┆ 2.6040e-7  │
│ 1347979.5   ┆ 2.6040e-7  │
│ 1.3546e6    ┆ 2.6040e-7  │
│ 1.3548e6    ┆ 2.6040e-7  │
│ 1.5059e6    ┆ 2.6040e-7  │
└─────────────┴────────────┘


AMT_CREDIT_LIMIT_ACTUAL
181
shape: (181, 2)
┌─────────────────────────┬────────────┐
│ AMT_CREDIT_LIMIT_ACTUAL ┆ proportion │
│ ---                     ┆ ---        │
│ i64                     ┆ f64        │
╞═════════════════════════╪════════════╡
│ 0                       ┆ 0.196292   │
│ 4500                    ┆ 0.000289   │
│ 9000                    ┆ 0.000577   │
│ 13500                   ┆ 0.000628   │
│ 18000                   ┆ 0.000191   │
│ …                       ┆ …          │
│ 900000                  ┆ 0.008745   │
│ 1012500                 ┆ 0.000002   │
│ 1125000                 ┆ 0.000006   │
│ 1237500                 ┆ 0.000012   │
│ 1350000                 ┆ 0.000038   │
└─────────────────────────┴────────────┘


AMT_DRAWINGS_ATM_CURRENT
2268
shape: (2_268, 2)
┌──────────────────────────┬────────────┐
│ AMT_DRAWINGS_ATM_CURRENT ┆ proportion │
│ ---                      ┆ ---        │
│ f64                      ┆ f64        │
╞══════════════════════════╪════════════╡
│ null                     ┆ 0.195249   │
│ -6827.31                 ┆ 2.6040e-7  │
│ 0.0                      ┆ 0.694141   │
│ 45.0                     ┆ 0.000004   │
│ 90.0                     ┆ 0.000002   │
│ …                        ┆ …          │
│ 1.332e6                  ┆ 2.6040e-7  │
│ 1.35e6                   ┆ 0.000002   │
│ 1.3545e6                 ┆ 2.6040e-7  │
│ 1.67625e6                ┆ 2.6040e-7  │
│ 2.115e6                  ┆ 2.6040e-7  │
└──────────────────────────┴────────────┘


AMT_DRAWINGS_CURRENT
187005
shape: (187_005, 2)
┌──────────────────────┬────────────┐
│ AMT_DRAWINGS_CURRENT ┆ proportion │
│ ---                  ┆ ---        │
│ f64                  ┆ f64        │
╞══════════════════════╪════════════╡
│ -6211.62             ┆ 2.6040e-7  │
│ -1687.5              ┆ 2.6040e-7  │
│ -519.57              ┆ 2.6040e-7  │
│ 0.0                  ┆ 0.83937    │
│ 0.045                ┆ 0.000004   │
│ …                    ┆ …          │
│ 1992949.2            ┆ 2.6040e-7  │
│ 2.0600e6             ┆ 2.6040e-7  │
│ 2.115e6              ┆ 2.6040e-7  │
│ 2.2393e6             ┆ 2.6040e-7  │
│ 2.2871e6             ┆ 2.6040e-7  │
└──────────────────────┴────────────┘


AMT_DRAWINGS_OTHER_CURRENT
1833
shape: (1_833, 2)
┌────────────────────────────┬────────────┐
│ AMT_DRAWINGS_OTHER_CURRENT ┆ proportion │
│ ---                        ┆ ---        │
│ f64                        ┆ f64        │
╞════════════════════════════╪════════════╡
│ null                       ┆ 0.195249   │
│ 0.0                        ┆ 0.80154    │
│ 234.0                      ┆ 2.6040e-7  │
│ 280.8                      ┆ 2.6040e-7  │
│ 459.0                      ┆ 5.2079e-7  │
│ …                          ┆ …          │
│ 899437.5                   ┆ 2.6040e-7  │
│ 899910.0                   ┆ 5.2079e-7  │
│ 900000.0                   ┆ 5.2079e-7  │
│ 1.30275e6                  ┆ 2.6040e-7  │
│ 1.529847e6                 ┆ 2.6040e-7  │
└────────────────────────────┴────────────┘


AMT_DRAWINGS_POS_CURRENT
168749
shape: (168_749, 2)
┌──────────────────────────┬────────────┐
│ AMT_DRAWINGS_POS_CURRENT ┆ proportion │
│ ---                      ┆ ---        │
│ f64                      ┆ f64        │
╞══════════════════════════╪════════════╡
│ null                     ┆ 0.195249   │
│ 0.0                      ┆ 0.735772   │
│ 0.045                    ┆ 2.6040e-7  │
│ 0.225                    ┆ 2.6040e-7  │
│ 0.45                     ┆ 2.6040e-7  │
│ …                        ┆ …          │
│ 1.8402e6                 ┆ 2.6040e-7  │
│ 1896559.2                ┆ 2.6040e-7  │
│ 1.9335e6                 ┆ 2.6040e-7  │
│ 2.0600e6                 ┆ 2.6040e-7  │
│ 2.2393e6                 ┆ 2.6040e-7  │
└──────────────────────────┴────────────┘


AMT_INST_MIN_REGULARITY
312267
shape: (312_267, 2)
┌─────────────────────────┬────────────┐
│ AMT_INST_MIN_REGULARITY ┆ proportion │
│ ---                     ┆ ---        │
│ f64                     ┆ f64        │
╞═════════════════════════╪════════════╡
│ null                    ┆ 0.079482   │
│ 0.0                     ┆ 0.502268   │
│ 0.045                   ┆ 0.000039   │
│ 0.09                    ┆ 0.000044   │
│ 0.135                   ┆ 0.000015   │
│ …                       ┆ …          │
│ 126728.145              ┆ 2.6040e-7  │
│ 136760.625              ┆ 2.6040e-7  │
│ 188976.6                ┆ 2.6040e-7  │
│ 194198.31               ┆ 2.6040e-7  │
│ 202882.005              ┆ 2.6040e-7  │
└─────────────────────────┴────────────┘


AMT_PAYMENT_CURRENT
163210
shape: (163_210, 2)
┌─────────────────────┬────────────┐
│ AMT_PAYMENT_CURRENT ┆ proportion │
│ ---                 ┆ ---        │
│ f64                 ┆ f64        │
╞═════════════════════╪════════════╡
│ null                ┆ 0.199981   │
│ 0.0                 ┆ 0.101686   │
│ 0.045               ┆ 0.000413   │
│ 0.09                ┆ 0.000285   │
│ 0.135               ┆ 0.000355   │
│ …                   ┆ …          │
│ 2.115e6             ┆ 2.6040e-7  │
│ 2.2871e6            ┆ 2.6040e-7  │
│ 2.4365e6            ┆ 2.6040e-7  │
│ 2.4975e6            ┆ 2.6040e-7  │
│ 4.2892e6            ┆ 2.6040e-7  │
└─────────────────────┴────────────┘


AMT_PAYMENT_TOTAL_CURRENT
182957
shape: (182_957, 2)
┌───────────────────────────┬────────────┐
│ AMT_PAYMENT_TOTAL_CURRENT ┆ proportion │
│ ---                       ┆ ---        │
│ f64                       ┆ f64        │
╞═══════════════════════════╪════════════╡
│ 0.0                       ┆ 0.565637   │
│ 0.045                     ┆ 0.000116   │
│ 0.09                      ┆ 0.000153   │
│ 0.135                     ┆ 0.000101   │
│ 0.18                      ┆ 0.000146   │
│ …                         ┆ …          │
│ 2.115e6                   ┆ 2.6040e-7  │
│ 2.2870e6                  ┆ 2.6040e-7  │
│ 2.4365e6                  ┆ 2.6040e-7  │
│ 2.49525e6                 ┆ 2.6040e-7  │
│ 4.2783e6                  ┆ 2.6040e-7  │
└───────────────────────────┴────────────┘


AMT_RECEIVABLE_PRINCIPAL
1195839
shape: (1_195_839, 2)
┌──────────────────────────┬────────────┐
│ AMT_RECEIVABLE_PRINCIPAL ┆ proportion │
│ ---                      ┆ ---        │
│ f64                      ┆ f64        │
╞══════════════════════════╪════════════╡
│ -423305.82               ┆ 2.6040e-7  │
│ -270288.0                ┆ 2.6040e-7  │
│ -267615.0                ┆ 2.6040e-7  │
│ -241042.005              ┆ 2.6040e-7  │
│ -225000.0                ┆ 2.6040e-7  │
│ …                        ┆ …          │
│ 1.3054e6                 ┆ 2.6040e-7  │
│ 1325147.4                ┆ 2.6040e-7  │
│ 1.3293e6                 ┆ 2.6040e-7  │
│ 1.3548e6                 ┆ 2.6040e-7  │
│ 1.4723e6                 ┆ 2.6040e-7  │
└──────────────────────────┴────────────┘


AMT_RECIVABLE
1338878
shape: (1_338_878, 2)
┌───────────────┬────────────┐
│ AMT_RECIVABLE ┆ proportion │
│ ---           ┆ ---        │
│ f64           ┆ f64        │
╞═══════════════╪════════════╡
│ -420250.185   ┆ 2.6040e-7  │
│ -268834.545   ┆ 2.6040e-7  │
│ -261777.015   ┆ 2.6040e-7  │
│ -239950.485   ┆ 2.6040e-7  │
│ -224569.71    ┆ 2.6040e-7  │
│ …             ┆ …          │
│ 1.3293e6      ┆ 2.6040e-7  │
│ 1.3342e6      ┆ 2.6040e-7  │
│ 1.341252e6    ┆ 2.6040e-7  │
│ 1.3548e6      ┆ 2.6040e-7  │
│ 1.4933e6      ┆ 2.6040e-7  │
└───────────────┴────────────┘


AMT_TOTAL_RECEIVABLE
1339008
shape: (1_339_008, 2)
┌──────────────────────┬────────────┐
│ AMT_TOTAL_RECEIVABLE ┆ proportion │
│ ---                  ┆ ---        │
│ f64                  ┆ f64        │
╞══════════════════════╪════════════╡
│ -420250.185          ┆ 2.6040e-7  │
│ -268834.545          ┆ 2.6040e-7  │
│ -261777.015          ┆ 2.6040e-7  │
│ -239950.485          ┆ 2.6040e-7  │
│ -224569.71           ┆ 2.6040e-7  │
│ …                    ┆ …          │
│ 1.3293e6             ┆ 2.6040e-7  │
│ 1.3342e6             ┆ 2.6040e-7  │
│ 1.341252e6           ┆ 2.6040e-7  │
│ 1.3548e6             ┆ 2.6040e-7  │
│ 1.4933e6             ┆ 2.6040e-7  │
└──────────────────────┴────────────┘

### **Categorical Variables**

In [21]:
## Nominal Variables
for col in CATEGORICAL_NOMINAL_VARS:
    print(col)
    print(df[col].n_unique())
    print(df[col].value_counts(normalize=True).sort(col))
    print("\n")

SK_ID_PREV
104307
shape: (104_307, 2)
┌────────────┬────────────┐
│ SK_ID_PREV ┆ proportion │
│ ---        ┆ ---        │
│ i64        ┆ f64        │
╞════════════╪════════════╡
│ 1000018    ┆ 0.000001   │
│ 1000030    ┆ 0.000002   │
│ 1000031    ┆ 0.000004   │
│ 1000035    ┆ 0.000001   │
│ 1000077    ┆ 0.000003   │
│ …          ┆ …          │
│ 2843476    ┆ 0.000025   │
│ 2843477    ┆ 0.000022   │
│ 2843478    ┆ 0.000023   │
│ 2843493    ┆ 0.000004   │
│ 2843496    ┆ 0.000004   │
└────────────┴────────────┘


SK_ID_CURR
103558
shape: (103_558, 2)
┌────────────┬────────────┐
│ SK_ID_CURR ┆ proportion │
│ ---        ┆ ---        │
│ i64        ┆ f64        │
╞════════════╪════════════╡
│ 100006     ┆ 0.000002   │
│ 100011     ┆ 0.000019   │
│ 100013     ┆ 0.000025   │
│ 100021     ┆ 0.000004   │
│ 100023     ┆ 0.000002   │
│ …          ┆ …          │
│ 456244     ┆ 0.000011   │
│ 456246     ┆ 0.000002   │
│ 456247     ┆ 0.000025   │
│ 456248     ┆ 0.000006   │
│ 456250     ┆ 0.000003   │
└────────────┴────────────┘


NAME_CONTRACT_STATUS
7
shape: (7, 2)
┌──────────────────────┬────────────┐
│ NAME_CONTRACT_STATUS ┆ proportion │
│ ---                  ┆ ---        │
│ str                  ┆ f64        │
╞══════════════════════╪════════════╡
│ Active               ┆ 0.963056   │
│ Approved             ┆ 0.000001   │
│ Completed            ┆ 0.03357    │
│ Demand               ┆ 0.000355   │
│ Refused              ┆ 0.000004   │
│ Sent proposal        ┆ 0.000134   │
│ Signed               ┆ 0.002879   │
└──────────────────────┴────────────┘

In [23]:
# Ordinal Variables
for col in CATEGORICAL_ORDINAL_VARS:
    print(col)
    print(df[col].n_unique())
    print(df[col].value_counts(normalize=True).sort(col))
    print("\n")

### **Time Variables**

In [24]:
# Ordinal Variables
for col in TIME_VARS:
    print(col)
    print(df[col].n_unique())
    print(df[col].value_counts(normalize=True).sort(col))
    print("\n")

## **Removing Duplicates**

In [ ]:
df = df.unique(subset=PRIMARY_KEY, keep="first")

## **Missing Values**

### **Single Imputation**

In [15]:
# Only fill nulls where necessary to meet schema requirements
df = df.with_columns(
    [
        pl.col("AMT_DRAWINGS_ATM_CURRENT").fill_null(0),
        pl.col("AMT_DRAWINGS_OTHER_CURRENT").fill_null(0),
        pl.col("AMT_DRAWINGS_POS_CURRENT").fill_null(0),
        pl.col("AMT_INST_MIN_REGULARITY").fill_null(0),
        pl.col("AMT_PAYMENT_CURRENT").fill_null(0),
        pl.col("CNT_DRAWINGS_ATM_CURRENT").fill_null(0),
        pl.col("CNT_DRAWINGS_OTHER_CURRENT").fill_null(0),
        pl.col("CNT_DRAWINGS_POS_CURRENT").fill_null(0),
        pl.col("CNT_INSTALMENT_MATURE_CUM").fill_null(0),
    ]
)

### **Deletion**

In [16]:
df = df.filter(pl.col("NAME_CONTRACT_STATUS") != "Unknown")

## **Data Type Transformation**

In [17]:
for col in NUMERICAL_DISCRETE_VARS:
    df = df.with_columns(pl.col(col).cast(pl.Int64))

for col in NUMERICAL_CONTINUOUS_VARS:
    df = df.with_columns(pl.col(col).cast(pl.Float64))

for col in CATEGORICAL_NOMINAL_VARS:
    df = df.with_columns(pl.col(col).cast(pl.Categorical))

for col in TIME_VARS:
    df = df.with_columns(pl.col(col).str.to_datetime())

In [9]:
df.head()

shape: (5, 23)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ SK_ID_PREV ┆ SK_ID_CURR ┆ MONTHS_BA ┆ AMT_BALAN ┆ … ┆ CNT_INSTA ┆ NAME_CONT ┆ SK_DPD ┆ SK_DPD_DE │
│ ---        ┆ ---        ┆ LANCE     ┆ CE        ┆   ┆ LMENT_MAT ┆ RACT_STAT ┆ ---    ┆ F         │
│ i64        ┆ i64        ┆ ---       ┆ ---       ┆   ┆ URE_CUM   ┆ US        ┆ i64    ┆ ---       │
│            ┆            ┆ i64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆        ┆ i64       │
│            ┆            ┆           ┆           ┆   ┆ i64       ┆ cat       ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 2562384    ┆ 378907     ┆ -6        ┆ 56.97     ┆ … ┆ 35        ┆ Active    ┆ 0      ┆ 0         │
│ 2582071    ┆ 363914     ┆ -1        ┆ 63975.555 ┆ … ┆ 69        ┆ Active    ┆ 0      ┆ 0         │
│ 1740877    ┆ 371185     ┆ -7        ┆ 31815.225 ┆ … ┆ 30        ┆ Active    ┆ 0      ┆ 0         │
│ 1389973    ┆ 337855     ┆ -4        ┆ 236572.11 ┆ … ┆ 10        ┆ Active    ┆ 0      ┆ 0         │
│ 1891521    ┆ 126868     ┆ -1        ┆ 453919.45 ┆ … ┆ 101       ┆ Active    ┆ 0      ┆ 0         │
│            ┆            ┆           ┆ 5         ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

# **Cleaned Consolidated Data (CCD)**

Cleaned Consolidated Data (CCD) serves as a consolidated and reconciled repository of historical internal and external credit data, and acts as the foundational dataset for all regulatory model development and monitoring. This includes transactional, behavioural, and reference data at the account, customer, and product level. It has been subject to data quality validation and reconciliation processes against core IT systems. These include:

- Reconciliation to general ledger balances and servicing systems;
- Data quality reviews to ensure accuracy and internal consistency (e.g., checking for orphan records, missing values, illogical transitions).

In [ ]:
query = f"""
        CREATE OR REPLACE TABLE {CREDIT_CARD_BALANCE_CCD} AS
        SELECT * FROM df
    """

con.execute(query)

In [ ]:
# Perform DQA on credit card balance data
query = f"SELECT COUNT(*) as total_rows FROM {CREDIT_CARD_BALANCE_CCD}"
total_rows = con.execute(query).fetchone()[0]

success, validated_data = data_quality_assessment(
    CREDIT_CARD_BALANCE_CCD, CreditCardBalanceSchema, con, sample_size=total_rows
)

if success:
    print(
        "\n✅ Credit card balance (Cleaned) data quality assessment completed successfully"
    )
else:
    print("\n❌ Credit card balance (Cleaned) data quality assessment failed")

query = f"""DROP TABLE {CREDIT_CARD_BALANCE_CCD};"""
con.execute(query)

============================================================
DATA QUALITY ASSESSMENT: CREDIT_CARD_BALANCE_CCD
============================================================

🔍 1. COMPLETENESS ASSESSMENT
----------------------------------------
Total records in credit_card_balance_ccd: 3,840,312
Sample size for validation: 3,840,312 rows

Completeness by column (% non-null):
  ✅ SK_ID_PREV: 100.0%
  ✅ SK_ID_CURR: 100.0%
  ✅ MONTHS_BALANCE: 100.0%
  ✅ AMT_BALANCE: 100.0%
  ✅ AMT_CREDIT_LIMIT_ACTUAL: 100.0%
  ✅ AMT_DRAWINGS_ATM_CURRENT: 100.0%
  ✅ AMT_DRAWINGS_CURRENT: 100.0%
  ✅ AMT_DRAWINGS_OTHER_CURRENT: 100.0%
  ✅ AMT_DRAWINGS_POS_CURRENT: 100.0%
  ✅ AMT_INST_MIN_REGULARITY: 100.0%
  ✅ AMT_PAYMENT_CURRENT: 100.0%
  ✅ AMT_PAYMENT_TOTAL_CURRENT: 100.0%
  ✅ AMT_RECEIVABLE_PRINCIPAL: 100.0%
  ✅ AMT_RECIVABLE: 100.0%
  ✅ AMT_TOTAL_RECEIVABLE: 100.0%
  ✅ CNT_DRAWINGS_ATM_CURRENT: 100.0%
  ✅ CNT_DRAWINGS_CURRENT: 100.0%
  ✅ CNT_DRAWINGS_OTHER_CURRENT: 100.0%
  ✅ CNT_DRAWINGS_POS_CURRENT: 100.0%
  ✅ CNT_INSTALMENT_MATURE_CUM: 100.0%
  ✅ NAME_CONTRACT_STATUS: 100.0%
  ✅ SK_DPD: 100.0%
  ✅ SK_DPD_DEF: 100.0%

🔍 2. SCHEMA VALIDATION (ACCURACY & UNIQUENESS ASSESSMENT)
----------------------------------------
✅ Schema validation & Uniqueness assessment PASSED
   - All 3840312 sample records conform to schema

🔍 3. TIMELINESS ASSESSMENT
----------------------------------------
  ⚠️ No datetime columns detected for timeliness assessment

📊 DQA SUMMARY
----------------------------------------
  Schema Compliance: ✅ PASSED
  Sample Size: 3,840,312 / 3,840,312 records
  Avg Completeness: 100.0%

✅ Credit card balance (Cleaned) data quality assessment completed successfully

In [ ]:
os.chdir(INTERIM_DATA_DIR)
df.write_parquet(f"{CREDIT_CARD_BALANCE_CCD}")

In [21]:
con.close()